# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swall < Formula
  desc "The task board where agents work alongside your team."
  homepage "https://swall.app"
  version "0.2.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/30xcompany/swall-releases/releases/download/v0.2.21/swall_darwin_amd64.tar.gz"
      sha256 "6db753f7255b135283acc505f371cfc06d2f0dacb228cb3764fbb7634962875c"

      define_method(:install) do
        bin.install "swall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/30xcompany/swall-releases/releases/download/v0.2.21/swall_darwin_arm64.tar.gz"
      sha256 "7cb0889d6bbe15d9a3d50b331152ce7e88fc8288eaa573f05245bedc05e782ed"

      define_method(:install) do
        bin.install "swall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/30xcompany/swall-releases/releases/download/v0.2.21/swall_linux_amd64.tar.gz"
      sha256 "1cc9624402a1f3afa4c1f028d58e389093f9e6bb3f2a4e7afc4753d065978202"
      define_method(:install) do
        bin.install "swall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/30xcompany/swall-releases/releases/download/v0.2.21/swall_linux_arm64.tar.gz"
      sha256 "b43cb236fcb3e459c8167da247ba88eb66a0dc2b77afb22ad2e3933a7d558d09"
      define_method(:install) do
        bin.install "swall"
      end
    end
  end

  test do
    system "#{bin}/swall --version"
  end
end
